# Generated by Django 4.1.7 on 2023-03-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='inventory.productinventory'),
        ),
    ]
